name: Deploy to Azure Static Web Apps
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # No build step – repo has index.html at root
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"      # files at repo root
          output_location: ""    # empty = no build output folder
          # leave api_location blank (your API is a separate Function App)
